version: '3.4'

services:
  or.micro.customers:
    image: ${DOCKER_REGISTRY-}ormicrocustomers
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile
    depends_on:
      - "rabbitmq"

  or.micro.orders:
    image: ${DOCKER_REGISTRY-}ormicroorders
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
    depends_on:
      - "rabbitmq"


  or.micro.products:
    image: ${DOCKER_REGISTRY-}ormicroproducts
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    depends_on:
      - "rabbitmq"


  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    depends_on:
      - "or.micro.products"
      - "or.micro.orders"
      - "or.micro.customers"


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
         - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
         - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
         - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
        RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
        - 5672:5672
        - 15672:15672
